//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonozWeb.Shared.Locals {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BonozWeb.Shared.Locals", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome
        {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your new app..
        /// </summary>
        public static string MenuAbout
        {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        public static string MenuCart
        {
            get {
                return ResourceManager.GetString("MenuCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string MenuContact
        {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuLogin
        {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string MenuOurService
        {
            get {
                return ResourceManager.GetString("MenuOurService", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string MenuRegister
        {
            get
            {
                return ResourceManager.GetString("MenuRegister", resourceCulture);
            }
        }

		 /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

		public static string Username
        {
            get
            {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
		
		public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
		
		 public static string EnterName
        {
            get
            {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }

		public static string EnterUsername
        {
            get
            {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
		
		public static string EnterPassword
        {
            get
            {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
		
		public static string Register
        {
            get
            {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
		
		public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
		
		public static string HomeTitle
        {
            get
            {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
		
		public static string HomeDescription
        {
            get
            {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }

    }
}
